### ISSUE TITLE
Disable smart input method

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#10]
The input method changes `--` to –, so it's kind of hard to write comments. See "smart dashes" setting in Interface Builder.

**Comment by markokoleznik** [comment]
Please check if this bug is still there, I can't reproduce it.

Fixed in:
https://github.com/markokoleznik/agda-writer/commit/9c2717ad4607e6568a2068bdd627d70c2abd2fe8

**Comment by andrejbauer** [comment]
Still not working with d3488a960aa9ffd963f1ee35aa6b77dfe3d54fa1

**Comment by markokoleznik** [comment]
strange, all "smart" inputs are disabled... Can you write double dashes in Emacs and/or Atom, for example?

**Comment by andrejbauer** [comment]
Safari, Emacs, Sublime Text 2, TextEdit, Microsoft Word: in all of these `--` is `--`. In Agda Writer `--` is `–`.

**Comment by markokoleznik** [comment]
Thanks, will look into that.

**Comment by markokoleznik** [comment]
Now?
https://github.com/markokoleznik/agda-writer/commit/460199f5e89e46756ddbaf8cf6d60a29571d8181

**Comment by markokoleznik** [comment]
Can you try this: 
Open a document and go to `Edit -> Substitutions -> Smart Dashes` and make sure it's unchecked.
Please let me know if that helped. In that case I will remove all those unnecessary stuff from Menu.

**Comment by andrejbauer** [comment]
According to the [Agda wiki](http://wiki.portal.chalmers.se/agda/pmwiki.php?n=ReferenceManual.Modules#import) module `A.B.C` is in file `A/B/C.agda` relative to the current file. Additionally, we may pas `--include-path=DIR` to the executable and it will look for modules in `DIR`. I think this is what you had in mind, correct? You want to have a preference for including additional directories. By the way, you could just have a preference for command-line options that need to be passed to Agda. Or can they already be specified when you specify the executable?

**Comment by markokoleznik** [comment]
Now it started doing the same to me, too :smile:

**Comment by markokoleznik** [comment]
Fixed in https://github.com/markokoleznik/agda-writer/commit/75710bd8dedc9ee684686081d051c28cfc15191c
