### ISSUE TITLE
Parse \ as backslash

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#12]
Parse `\` as '`, that is in Agda the backslash is an _ordinary_ charater (actually, it stands for lambda).

**Comment by markokoleznik** [comment]
Couldn't I just send `\` to agda? In obj-C I just replace `\` with `\\`, but the actual string (which will be sent to Agda) will only contain one `\`

**Comment by markokoleznik** [comment]
I think now it's ok.

https://github.com/markokoleznik/agda-writer/commit/4c70fbddabcb7209b46d37e1f41d9889a7604e74
