### ISSUE TITLE
How to type Unicode

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#13]
1. We can have a translation table which maps words to words, possibly configurable through Preferences.
2. Whenever the user types a whitespace character, we look at the word at the cursor and map it using the translation table.
3. We may also add a command which tokenizes everything in a file (or in the selection if there is a selection).

**Comment by banacorn** [comment]
This is how I handle the input method, looks nasty though
https://github.com/banacorn/agda-mode/blob/master/lib/input-method.coffee

**Comment by markokoleznik** [comment]
I'm doing this right now. The best solution I found is to map the most used commands with unicode characters. Plus side of this is that autocomplete works "almost" out of the box :)

**Comment by markokoleznik** [comment]
Done in:
https://github.com/markokoleznik/agda-writer/commit/d3488a960aa9ffd963f1ee35aa6b77dfe3d54fa1
