### ISSUE TITLE
How to close the "normalize" dialog?

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#17]
In the "normalize" input dialog, how do I cancel it? `Esc` does not seem to work.

**Comment by markokoleznik** [comment]
Thanks, I din't have time to properly implement this yet, since I'm preparing another window for goal specific normalize actions...

**Comment by markokoleznik** [comment]
Window now closes when `esc` is pressed or when window loses focus (when we click away)

**Comment by andrejbauer** [comment]
A pišeš magisterij? ;-)

**Comment by banacorn** [comment]
haha is that Slovene?

**Comment by markokoleznik** [comment]
Haha, yes :) @andrejbauer is my mentor and he's asking if I'm writing my masters :D

**Comment by banacorn** [comment]
I'm doing my master's, too :D

**Comment by andrejbauer** [comment]
According to the commit log he's fiddling with the GUI instead of writing his thesis.

**Comment by markokoleznik** [comment]
Is `agda-mode` also a part of your master's? :D

**Comment by banacorn** [comment]
It's just a tool for my thesis, but now my mentor is using it  :p

**Comment by markokoleznik** [comment]
Nice! :) Anyway, we should continue this debate on [agda-mode Gitter](https://gitter.im/banacorn/agda-mode), if that is alright with you :D

**Comment by banacorn** [comment]
:+1:
