### ISSUE TITLE
Auto-complete too eager

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#18]
Suppose I have the following text:

```
g : Set -> Set
g x = x
```

and I place the cursor just _after_ the `=` sign. Then autocomplete shows up an offers that I change `=` to `⇒`. This is slightly annoying but ok. Then if I press `Esc` to cancel the suggestion, it shows up again and it seems hard to get rid of it. Also, it is annoying that any movement (say right arrow key) _confirms_ the suggestion.

I would rather see auto-complete mini-windows disabled than showing up like this in annoying ways. Even if it is a user-defined preference, auto-complete shouldn't be popping up quite so eagerly.

**Comment by andrejbauer** [comment]
Here is a _very_ annoying situation. I have

```
g x = x
```

with the cursor at the end of line. Then if I keep pressing left arrow slowly, as my cursor moved it will change `=` to `=>`. Auto-complete should _not_ work like this.

**Comment by markokoleznik** [comment]
How about this: Autocomplete can be enabled only if user presses escape key? Escape key for triggering autocomplete is also in xcode as is in default implementation of autocomplete. Not sure if I can disable popup window though...

**Comment by andrejbauer** [comment]
It is ok for the popup window to show up when the user activated autocomplete. I am complaining about the fact that it pops up when I move around the text. For instance, I move down, down, down, happen to land next to a `=`, autocomplete shows up, I move down again and my `=` changes to `=>`!

Is Esc really used for autocomplete? In Eclipse it is Ctrl+Space, in Sublime Text it is Tab or Alt-Tab (I do not remember which).

**Comment by markokoleznik** [comment]
Yes, I tried that right now. 
I can disable showing popup window when user presses one of the arrow keys. Would this help autocomplete to behave more politely?

**Comment by markokoleznik** [comment]
fixed in: https://github.com/markokoleznik/agda-writer/commit/e8cf3ddb80f595c87a5c2cf5709bd2d0bc72fb36

Should be ok now...
