### ISSUE TITLE
Line numbers and error messages

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#19]
There are no line numbers and there is no way to move automagically to the error reported by Agda, so this leaves the user in a hopeless situation. Two possible solutions would be to:
1. Display line numbers.
2. Parse error messages and make them active so that clicking on them places the cursor onto the location.

**Comment by markokoleznik** [comment]
both of those suggestions are on todo list :)

**Comment by markokoleznik** [comment]
Main text window now shows line numbers. Any message that has range in it (line number and range) are now parsed with custom Tokens, so when user presses that token, it selects that part of the string.

I can change color of tokens if they are too "shiny"
