### ISSUE TITLE
Add included libraries when sending action

### ISSUE THREAD

**Issue by markokoleznik** [markokoleznik/agda-writer#22]
User can add libraries when interacting with Agda. Libraries can be included in Preferences.

**Comment by andrejbauer** [comment]
Are we sure abot this? Usually the libraries are imported explicitly at the top of the file. Or did you mean a directory in which such libraries are located?

**Comment by markokoleznik** [comment]
Yes, I think I was unclear.  I meant external libraries, like stdlib for Agda. Otherwise, if I'm not mistaken, you just put `import somefile` at the top of the file, right? That looks in the same directory as where the  current file is? Or it looks recursively in the folders?

**Comment by andrejbauer** [comment]
According to the Agda wiki module A.B.C is in file A/B/C.agda relative to the current file. Additionally, we may pas --include-path=DIR to the executable and it will look for modules in DIR. I think this is what you had in mind, correct? You want to have a preference for including additional directories. By the way, you could just have a preference for command-line options that need to be passed to Agda. Or can they already be specified when you specify the executable?

**Comment by markokoleznik** [comment]
When sending Load or Compile action to Agda, we specify two parameters: 
1.) file path to our "script"
2.) file path to our external libraries (separated with comma)
I just added a field in preferences, so the user can specify external libraries that are included upon loading/compiling. 

If you think people would use command line options, I can also add that in Preferences.

**Comment by andrejbauer** [comment]
Command-line options are probably not that necessary, since they are also available as pragmas at the top of a file.

**Comment by markokoleznik** [comment]
Ok I will then close this issue.
