### ISSUE TITLE
Package Agda with agda-writer

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#25]
The Agda license allows that the Agda executable be packaged with another piece of software. It would be a complete win if we could package Agda with agda-writer and bring the cost of installation down to zero: just get it from the AppStore and viola!

**Comment by markokoleznik** [comment]
How difficult would that be? I'm not that fluent in this kind of programming, but if I'm not mistaken, it would  require some bash scripting? First, we need cabal (if it's not installed already) and on top of that we need to install Agda. Any suggestions would be obliged  :)

**Comment by andrejbauer** [comment]
Agda is a compiled executable, it would just live as an executable ina subfolder of Agda Writer, together with whatever files it wants to have. I can help.

**Comment by markokoleznik** [comment]
Sounds good!

**Comment by markokoleznik** [comment]
I tried that and I think that would be quite hard. If I just copy agda executable and run it from another mac, i get `/Users/markokoleznik/Library/Haskell/share/ghc-7.8.3-x86_64/Agda-2.4.2.2/lib/prim/Agda/Primitive.agda:
openFile: does not exist (No such file or directory)`.

I'm quite sure that Agda needs to be compiled on the machine before using compiled file `agda`.
I'm not sure if there is any other way around that. One possible way is to run a terminal commands inside Agda Writer that installs agda. Any suggestion?

**Comment by banacorn** [comment]
Does it need other stuffs other than the executable itself?

**Comment by markokoleznik** [comment]
Well, if you compile it on your computer, then executable agda file will suffice. Like I said, I tried on other mac computer and Agda responds (starts in interactive mode). But as soon as I request something (Load file, for example) it responds with error. Funny thing is, it tries to look in MY folder, not the folder used by other computer... So I'm quite sure you need to compile it on your own computer in order to use compiled file of Agda properly.

**Comment by andrejbauer** [comment]
This is a solvable problem. I don't actually believe that just the executable will suffice. At the very least we want to include the standard library.

**Comment by banacorn** [comment]
Something just popped up in my head ... why don't we build a web service that serves Agda?

**Comment by andrejbauer** [comment]
Go ahead, but let Marko study for his qualifying exam first :-)

**Comment by banacorn** [comment]
:four_leaf_clover:

**Comment by markokoleznik** [comment]
@banacorn I think that is actually doable... If you're serious about that, I would like to help. Agda will need some proper API sooner or later. But as @andrejbauer said, I'm studying now for my (hopefully) final exam :D 

Just for curiosity... What you had in mind? Apache server + RESTful service?

**Comment by banacorn** [comment]
Sorry I don't actually meant "web" service, just IPC now travels over internet, with session management.

Good luck with your exam :D

**Comment by markokoleznik** [comment]
Huh, I have no idea how to do that :D 

Thanks!

**Comment by markokoleznik** [comment]
Tested on 6 different macs, it seems it should be working.
