### ISSUE TITLE
Make this cross-platform

### ISSUE THREAD

**Issue by turion** [markokoleznik/agda-writer#26]
Can you modify it so it compiles on linux?

**Comment by andrejbauer** [comment]
Santa Claus will do that.

**Comment by markokoleznik** [comment]
I'm affraid not.
Objective-C uses Coca framework and there is no way to compile it for different platforms as far as I know.

**Comment by banacorn** [comment]
@turion sorry I'm not Santa Claus XD, but maybe you can try the [agda-mode](https://atom.io/packages/agda-mode) I built for Atom, which should work on linux

**Comment by markokoleznik** [comment]
@banacorn :+1: 
Well, I think this discussion may be closed.

**Comment by turion** [comment]
@banacorn, great, I'll check it out!
