### ISSUE TITLE
Insert spaces when hitting 'tab' key

### ISSUE THREAD

**Issue by scott-fleischman** [markokoleznik/agda-writer#28]
Perhaps how many spaces to insert can be a configurable setting.

**Comment by markokoleznik** [comment]
It seems obvious enough... Is there any standard how many spaces represents tab? Two?

**Comment by markokoleznik** [comment]
User can configure number of spaces when Tab is pressed.

Commit: https://github.com/markokoleznik/agda-writer/commit/2a0335c7dc8edc3c67e4dad0a3600b58b1036370

Screenshot: 
![screen shot 2015-11-07 at 21 57 35](https://cloud.githubusercontent.com/assets/8185285/11017301/055d1a08-859b-11e5-8aac-81248374ff06.png)

Would that be ok?

**Comment by scott-fleischman** [comment]
Looks great thanks!
