### ISSUE TITLE
Issue with multiple libraries...

### ISSUE THREAD

**Issue by markokoleznik** [markokoleznik/agda-writer#32]
Strangley, it seems to look into given directory but still "throws" an error.

**Comment by andrejbauer** [comment]
What are you talking about?

**Comment by markokoleznik** [comment]
User can specify multiple paths to some external libraries and when using `import` it should look in ALL the folders specified in Settings... I'm guessing I don't parse paths correctly.

![screen shot 2015-12-08 at 10 39 10](https://cloud.githubusercontent.com/assets/8185285/11652460/397aada4-9d98-11e5-98c3-cd17203700bd.png)

**Comment by banacorn** [comment]
By the way there's a new library management system coming
http://agda.readthedocs.org/en/latest/tools/package-system.html
https://github.com/agda/agda/issues/1693#issuecomment-161059770
