### ISSUE TITLE
Can't launch Agda it seems

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#5]
I set my Agda executable in preferences to `/Users/andrej/.cabal/bin/agda` and as far as I can tell this is correct. However, this seems insufficient to launch Agda. How can I perform further tests to see what actually died? The output window shows that the launch response was empty.

**Comment by markokoleznik** [comment]
This part needs to be rewritten.
Anyway, quick hack has been added in this commit (latest one):
https://github.com/markokoleznik/agda-writer/commit/03f2d0f32541e5116b906df88870b2664ec0e735
Write path to agda "by hand". Copy & Paste functionality is not yet implemented in this controller.
in my case:
/Users/markokoleznik/Library/Haskell/bin/agda
Hit enter and close preferences window. Test agda should give response.

**Comment by banacorn** [comment]
I'm wondering if it's possible to get the path of Agda executable automatically.
I've tried something like `which agda` but it seems that the program doesn't have enough permissions to do so :p

**Comment by markokoleznik** [comment]
@banacorn how about terminal command to search folder named `agda`?
I was playing around and end up with command:
`find ~/ -name "agda"` which looks in users directory (search without `~` is way to slow and to many Permission denied results are involved)

Will try to implement that, I'll get back to you :)

**Comment by markokoleznik** [comment]
@banacorn Command above works like a charm. I guess it should work for you too (hopefully without problems with permissions).

**Comment by banacorn** [comment]
Thanks, it works!!!

**Comment by andrejbauer** [comment]
It's not quite safe to use just any executable called `agda`, and you will annoy people by running `find` on their home directories (it can take a long time). Here would be reasonable places to look for Agda, in order of likelihood:
- `$HOME/.cabal/bin/agda`
- `/usr/local/bin/agda`
- the output of `/usr/bin/which agda`

After that you should give up. The `find` command can find a lot of stuff. At least run it so that it looks for an executable named Agda, not any file:

```
 find $HOME -name agda -a -perm -u+x
```

Note that it will find _all_ such executables, one per line of output.

**Comment by andrejbauer** [comment]
My problem is that I actually provided the Agda location in the preferences, but it's still not found. I suppose I shoud run it with debugger to see what ecutable it's actually trying to find.

**Comment by markokoleznik** [comment]
Thanks, will try that. As for that problem, I'll commit new stuff later this evening (still doing some polishing).

**Comment by markokoleznik** [comment]
Try this commit:
https://github.com/markokoleznik/agda-writer/commit/2797b333be0670b4503e88515f9aa4ea1a907a46
It still needs some work to do on Preferences class (spinner, ok sign, etc) but setting path should work...
By the way, Copy & Paste functionality is not yet implemented, but manually setting the path should work.

**Comment by markokoleznik** [comment]
To answer about testing:
You probably launch application from Xcode, right? So, one the left side there is a Show the breakpoint navigator. 
![screen shot 2015-05-01 at 19 16 04](https://cloud.githubusercontent.com/assets/8185285/7433944/8e976c60-f036-11e4-8712-92a7a3554e59.png)

You probably won't see All Exceptions.
For that, open (Menu ->) Debug -> Breakpoints -> Create Exception Breakpoint

Now every time exception is raised, debugger will stop and show that line of code.
