### ISSUE TITLE
Where to look for the agda executable?

### ISSUE THREAD

**Issue by andrejbauer** [markokoleznik/agda-writer#7]
Reasonable places to look:
- `~/.cabal/bin/agda`
- `~/Library/Haskell/bin/agda`
- `/Library/Haskell/bin/agda`

The procedure:
1. If executable is set in preferences, use that.
2. If `agda` found in `PATH` then use that (but do not set in preferences).
3. If not found, then open a dialog for the user to specify `agda`.
4. The dialog may provide a default choice, namely `agda` found in one of the reasonable places above (but user must confirm this choice, and has the ability to change).
5. The choice made by the user is remembered. Henceforth he can change the executable through Preferences.

**Comment by markokoleznik** [comment]
It would take me quite a lot time to implement behavior stated above, so I used the next approach: Upon first launch, agda path is not set by default. It looks in places above and as soon as it finds one, it sets that one as default. If it fails to find agda in places above, it does nothing, but it keeps bugging user until valid path is set in preferences controller. User can always change path to agda, as long as the path is valid (i.e. task is launched). 

This issue can be reopened.
